### ISSUE TITLE
Copyright Notice

### ISSUE THREAD

**Issue by GreenFleece** [miachm/SODS#10]
Could you include a copyright notice somewhere in your distribution? A copyright line in the README would suffice.

**Comment by miachm** [comment]
I am not familiar with that concept. What is a copyright notice?

**Comment by GreenFleece** [comment]
The copyright notice is a line of text to state who the owner of the copyright is. In other words, it's stating that the code belongs to you if any legal issues arise due to the copyright.

In it's simplest form, it's the following printed somewhere in your code:
Copyright {yyyy} {name of copyright owner}

With the year replaced with the current year and the owner replaced with your name.

In order for the Apache License to apply, you need to include a copyright notice somewhere in your code.
From the license text:

      "Work" shall mean the work of authorship, whether in Source or
      Object form, made available under the License, as indicated by a
      copyright notice that is included in or attached to the work
      (an example is provided in the Appendix below).
      ...
      Copyright {yyyy} {name of copyright owner}

The library is great and I would love to include it in a distributed product, but I can't get legal approval to use it unless you include the notice.

**Comment by miachm** [comment]
@GreenFleece i added a copyright notice at the README.MD.

**Comment by lbyzx123** [comment]
when load 500 rows record:
Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.github.miachm.sods.Range.getValues(Range.java:226)
	at com.packagemanage.service.impl.ODSParserUtils.getHeaderFromSheet(ODSParserUtils.java:92)

**Comment by lbyzx123** [comment]
when load 500 rows records:
Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.github.miachm.sods.Range.getValues(Range.java:226)
	at com.packagemanage.service.impl.ODSParserUtils.getHeaderFromSheet(ODSParserUtils.java:92)

**Comment by lbyzx123** [comment]
when load 500 rows record:
Caused by: java.lang.OutOfMemoryError: Java heap space
at com.github.miachm.sods.Range.getValues(Range.java:226)
at com.packagemanage.service.impl.ODSParserUtils.getHeaderFromSheet(ODSParserUtils.java:92)

**Comment by lbyzx123** [comment]
<dependency>
    <groupId>com.github.miachm.sods</groupId>
    <artifactId>SODS</artifactId>
    <version>1.1.1</version>
</dependency>

when load 500 rows record:
Caused by: java.lang.OutOfMemoryError: Java heap space
at com.github.miachm.sods.Range.getValues(Range.java:226)
at com.packagemanage.service.impl.ODSParserUtils.getHeaderFromSheet(ODSParserUtils.java:92)

**Comment by miachm** [comment]
@lbyzx123 Please open a new issue about that problem.

I need more info to recreate the problem in my computer.

Thanks
