### ISSUE TITLE
Add ability to open password protected sheets

### ISSUE THREAD

**Issue by rnveach** [miachm/SODS#87]
A password protected ODS is throwing the following exception:
````
java.util.zip.ZipException: only DEFLATED entries can have EXT descriptor
	at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:313)
	at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:125)
	at com.github.miachm.sods.Uncompressor.nextFile(Uncompressor.java:17)
	at com.github.miachm.sods.OdsReader.load(OdsReader.java:51)
	at com.github.miachm.sods.OdsReader.load(OdsReader.java:38)
	at com.github.miachm.sods.SpreadSheet.<init>(SpreadSheet.java:61)
	at com.github.miachm.sods.SpreadSheet.<init>(SpreadSheet.java:48)
	at Test.main(Test.java:15)
````

Duplicating the file with no password works without issue.

Code used is the same as `BasicUsage` in the readme.

**Comment by miachm** [comment]
Added support for encrypted files in 1.9.0. Now it should work

**Comment by rnveach** [comment]
Thank you, it works now.
